language: python
python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coverage codecov
  - python setup.py develop

script:
  - coverage erase
  - coverage run -p -m nose.core -v vixen/tests
  - coverage combine

after_success:
  - coverage report
  - codecov
