language: python
python:
  - 2.7
  - 3.6

addons:
  firefox: latest

install:
  - pip install -r requirements.txt
  - pip install coverage codecov selenium
  - python setup.py develop

before_script:
  - firefox --version
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage erase
  - coverage run -p -m nose.core -v vixen/tests
  - coverage run -p -m nose.core -v vixen/integration_tests
  - coverage combine

after_success:
  - coverage report
  - codecov
