environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe setup.py develop"

test_script:
  - "%PYTHON%\\python.exe -m pytest -v vixen\\tests"
